server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labdb
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: jwlee20541@gmail.com
    password: olkynnqbssbbuuvj
    properties:
      mail:
        smtp:
          auth: true 
          starttls: 
            enable: true 
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

# warning 발생 시 setting에서 설정 변경
com:
  mlp:
    upload:
      path: upload

logging:
  level:
    com:
      springframework:
        security:
          web: trace
      
